config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index' # index itself should be the root
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/delete'
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/create'
  # get 'cocktails/edit'
  # get 'cocktails/update'
  # get 'cocktails/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    # now doses are nested within the cocktail routes
     # so they get prepended with 'cocktails/:cocktail_id'
    resources :doses, only: [:new, :create] # only establishes routes for the ones in brackets
  end

  resources :doses, only: [:destroy] # deleting an ingredient you only need the id of the dose not the one of the cocktails prepended
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy # delete child doses once deleted
  has_many :ingredients, through: :doses # through doses which is why this comes after doses
  validates :name, uniqueness: true, presence: true, allow_blank: false
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true, allow_blank: false # alternative frmo Bugi: validates_uniqueness_of :cocktail, scope: :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :edit, :update, :destroy]

  def index # GET /cocktails
    @cocktails = Cocktail.all
  end

  def show # GET /cocktails/1
    # @cocktail = Cocktail.find(params[:id]) # refactoring >>> own method below + before_action
  end

  def new # GET /cocktails/new
    @cocktail = Cocktail.new # Empty instance of the cocktail to display in the form (=> new view)
  end

  def create # POST /cocktails
    @cocktail = Cocktail.new(cocktail_params)
    # @cocktail.save # outdated since if logic is better
    if @cocktail.save
      redirect_to cocktail_path(@cocktail.id), notice: 'Cocktail was successfully created.' # define where to go to after submitting form (site will reload)
    else
      render(:new) # rendering does not execute the new method (again), instead it only uses the view of new (to display errors when filling in the form)
    end
  end

  def edit # GET /cocktails/1/edit
    # @cocktail = Cocktail.find(params[:id]) # refactoring >>> own method below + before_action
  end

  def update  # PATCH/PUT /cocktails/1
    # @cocktail = Cocktail.find(params[:id]) # refactoring >>> own method below + before_action
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail.id), notice: 'Cocktail was successfully updated.'
  end

  def destroy # DELETE /cocktails/1
    # @cocktail = Cocktail.find(params[:id]) # refactoring >>> own method below + before_action
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def find_cocktail # to be used in combination with the before_action from the top
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id]) # params is a hash and we have to call it by the right id
    @ingredients = Ingredient.all
    @dose = Dose.new # Empty instance to display in the form
  end
  def create
    @cocktail = Cocktail.find(params[:cocktail_id]) # find cocktail with id given in params and save in var
    @dose = Dose.new(dose_params) # create a dose with name/ingredient_id allowed in strong params
    # @dose.cocktail # this gives me back the cocktail instance that the dose belongs to
    @dose.cocktail = @cocktail # writing /setting the cocktail that the dose belongs to. here I give a cocktails ID to the dose (for the dose to exist it needs a cocktail id (and ingredient id))
    # similar to attr_accessor from OOP
    if @dose.save
      redirect_to cocktail_path(@cocktail) # this will go to '/cocktails/:id' of the @cocktail
    else
      render :new # rendering does not execute the new method (again), instead it only uses the view of NEW (to display validation errors when filling in the form)
    end
  end
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private
  # Only allow a trusted parameter "white list" through.
  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id) # here check what is coming in from the parameters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<div class="container">
<h1>Edit cocktail</h1>
<%= render 'form' %>

<%= link_to 'Back', cocktail_path(@cocktail), class: 'btn btn-primary'  %>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1508253730651-e5ace80a7025?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80);">
  <h1>They say everything looks better with a drink</h1>
  <h2>...well, think again</h2>
</div>
<div class="container" >
  <div class="product-card mt-5">
    <% @cocktails.each do |coc| %>
      <div class="card-product mb-5">
          <img src="https://images.pexels.com/photos/338713/pexels-photo-338713.jpeg?cs=srgb&dl=pexels-isabella-mendes-338713.jpg&fm=jpg" alt="Cocktails">
          <h2><%= link_to coc.name, cocktail_path(coc)  %></h2>
      </div>
    <% end %>
  </div>

<div class="d-flex justify-content-center mb-5">
  <%= link_to 'Add cocktail', new_cocktail_path, class: 'btn btn-primary'  %>
</div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
<h1>Please enter the name of a new cocktail</h1>
<%= render 'form' %>

<div>
<%= link_to 'Back', cocktails_path, class: 'btn btn-primary'  %>
</div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %> </h1>

    <%= cl_image_tag @cocktail.photo.key, class: "mr-3", height: 300, width: 400, crop: :fill if @cocktail.photo.attached?%>
  <p>
    <strong>Ingredients:</strong>
  </p>
    <% @cocktail.doses.each do |dose| %>
    <p><%= dose.description %> <%= dose.ingredient.name %><%= link_to "🗑", cocktail_path(@cocktail.id), method: :delete, data: {confirm: 'Are you sure?'} %></p>
    <hr>
    <% end %>

  <div>
    <%= link_to 'Back', cocktails_path(@cocktails), class: "btn btn-primary"   %>
    <%= link_to 'Edit', edit_cocktail_path(@cocktail.id), class: "btn btn-warning"   %>
    <%= link_to 'Delete cocktail', cocktail_path(@cocktail), class: "btn btn-danger", method: :delete, data: {confirm: 'Are you sure you want to delete this cocktail?'} %>
  </div>

  <div>
    <h1>Add an ingredient</h1>
    <%= simple_form_for([@cocktail, Dose.new]) do |f| %>
      <%= f.input :description %>
      <%= f.input :ingredient_id, as: :select, collection: Ingredient.all.order(:name) %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/doses/_form.html.erb
<div class="container">
<h1>Add an ingredient</h1>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, as: :select, collection: Ingredient.all.order(:name) %>
  <%= f.submit %>
<% end %>

</div>

app/views/doses/new.html.erb
<div class="Container">
<h1>New Ingredient for <%= @cocktail.name %></h1>
<%= render 'form' %>

<%= link_to 'Back', cocktails_path(@cocktails), class: "btn btn-primary"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div>

    </div>
    <div class="background"> <%= yield %> </div>
  </body>
</html>